apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-optimizer.fullname" . }}
  labels:
    {{- include "spark-optimizer.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.config.features.monitoring }}
    - port: {{ .Values.config.websocketPort }}
      targetPort: websocket
      protocol: TCP
      name: websocket
    {{- end }}
  selector:
    {{- include "spark-optimizer.selectorLabels" . | nindent 4 }}
